aa

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,7 +8,7 @@ jobs:
     docker:
       # specify the version you desire here
       - image: circleci/php:7.1.5-browsers
-      
+
       # Specify service dependencies here if necessary
       # CircleCI maintains a library of pre-built images
       # documented at https://circleci.com/docs/2.0/circleci-images/
@@ -16,24 +16,23 @@ jobs:
 
     working_directory: ~/repo
 
-install_composer: &install_composer
-    command: |
-        cd /tmp
-        EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
-        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-        ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
-        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
-        then
-            >&2 echo 'ERROR: Invalid installer signature'
-            rm composer-setup.php
-            exit 1
-        fi
-        sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
-        RESULT=$?
-        rm composer-setup.php
-        exit $RESULT
+    - install_composer: &install_composer
+      command: |
+          cd /tmp
+          EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
+          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+          ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+          then
+              >&2 echo 'ERROR: Invalid installer signature'
+              rm composer-setup.php
+              exit 1
+          fi
+          sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
+          RESULT=$?
+          rm composer-setup.php
+          exit $RESULT
  
-	
     steps:
       - checkout
 
@@ -50,6 +49,6 @@ install_composer: &install_composer
           paths:
             - ./vendor
           key: v1-dependencies-{{ checksum "composer.json" }}
-        
+
       # run tests!
       - run: phpunit
